nations = ["Bulgaria",
           "New Zealand",
           "Sierra Leone",
           "Indonesia",
           "Tuvalu",
           "Algeria",
           "Georgia",
           "Central African ",
           "Panama",
           "Ireland",
           "Samoa",
           "Barbados",
           "Brazil",
           "South Africa",
           "Belgium",
           "Rawanda",
           "United States",
           "Laos",
           "Egypt",
           "Tanzania",
           "Italy",
           "Belarus",
           "Japan",
           "Australia",
           "Bahrain",
           "Chad",
           "Oman",
           "Zambia",
           "Ukraine",
           "San Marino",
           "Cuba",
           "Madagascar",
           "Liberia",
           "Paraguay",
           "Costa ",
           "Bhutan",
           "Lesotho",
           "Guyana",
           "Libya",
           "Botswana",
           "Palau",
           "Mongolia",
           "Burkina Faso",
           "Nauru",
           "Ethiopia",
           "Iceland",
           "Canada",
           "Azerbaijan",
           "Philippines",
           "Saint Kitts and Nevis",
           "South Korea",
           "Mali",
           "North Macedonia",
           "Singapore",
           "Spain",
           "Kiribati",
           "Honduras",
           "Mauritania",
           "United Arab Emirates",
           "Austria",
           "Haiti",
           "Solomon Islands",
           "Lithuania",
           "Mozambique",
           "Greece",
           "Gabon",
           "Djibouti",
           "Cameroon",
           "Finland",
           "Zimbabwe",
           "Montenegro",
           "Andorra",
           "Seychelles",
           "Uzbekistan",
           "Estonia",
           "Guinea-Bissau",
           "Sudan",
           "Jamaica",
           "Malawi",
           "Yemen",
           "Côte d’Ivoire",
           "Monaco",
           "Turkey",
           "Nepal",
           "Trinidad and Tobago",
           "Sri Lanka",
           "Bangladesh",
           "Luxembourg",
           "Czech ",
           "Maldives",
           "Equatorial Guinea",
           "North Korea",
           "Afghanistan",
           "El Salvador",
           "Antigua and Barbuda",
           "Denmark",
           "Lebanon",
           "Kosovo",
           "Cambodia",
           "Congo",
           "Peru",
           "Bosnia and Herzegovina",
           "Bahamas",
           "Papua New Guinea",
           "Fiji",
           "Uganda",
           "Guatemala",
           "Eswatini",
           "Moldova",
           "Serbia",
           "Iran",
           "Switzerland",
           "Bolivia",
           "France",
           "Comoros",
           "Qatar",
           "Malaysia",
           "Albania",
           "Micronesia",
           "Pakistan",
           "Cabo Verde",
           "Vanuatu",
           "Vietnam",
           "Saint Lucia",
           "Turkmenistan",
           "Liechtenstein",
           "Marshall Islands",
           "China",
           "Dominican ",
           "United Kingdom",
           "Grenada",
           "Ecuador",
           "Norway",
           "East Timor",
           "Germany",
           "Mauritius",
           "Syria",
           "Slovakia",
           "Colombia",
           "Tonga",
           "Eritrea",
           "Taiwan",
           "Kenya",
           "Dominica",
           "Togo",
           "Belize",
           "Hungary",
           "Angola",
           "India",
           "Cyprus",
           "Thailand",
           "Saudi Arabia",
           "Portugal",
           "Congo",
           "Russia",
           "Venezuela",
           "Sudan",
           "Suriname",
           "Jordan",
           "Kuwait",
           "Sweden",
           "Tunisia",
           "Nigeria",
           "Somalia",
           "Malta",
           "Senegal",
           "Benin",
           "Morocco",
           "Slovenia",
           "Poland",
           "Guinea",
           "Brunei",
           "Armenia",
           "Nicaragua",
           "Mexico",
           "Croatia",
           "Burundi",
           "Kyrgyzstan",
           "Chile",
           "Saint Vincent and the Grenadines",
           "Namibia",
           "Iraq",
           "Tajikistan",
           "Sao Tome and Principe",
           "Netherlands",
           "Niger",
           "Romania",
           "Myanmar (Burma)",
           "Vatican City",
           "Israel",
           "Uruguay",
           "Latvia",
           "Argentina",
           "Kazakhstan",
           "The Gambia",
           "Ghana", ]

countries = []

for nation in nations:
	countries.append(nation.lower())

destination = str(input("Please enter your preferred destination country."))
destination = destination.lower()

if destination in countries:
	print(f"{destination.title()} is in the list of approved countries.")
else:
	print(f"{destination.title()} is not in the list of approved countries.")

if destination not in countries:
	print(f"{destination.title()} is not in the list of approved countries.")
else:
	print(f"{destination.title()} is in the list of approved countries.")
